/*
 * Copyright (C) 2020 BlueKitchen GmbH
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 * 4. Any redistribution, use, or modification is done solely for
 *    personal benefit and not for any commercial purpose or for
 *    monetary gain.
 *
 * THIS SOFTWARE IS PROVIDED BY BLUEKITCHEN GMBH AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BLUEKITCHEN
 * GMBH OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * Please inquire about commercial licensing options at
 * contact@bluekitchen-gmbh.com
 *
 */

#define BTSTACK_FILE__ "hog_host_demo.c"

/* EXAMPLE_START(hog_host_demo): HID Host LE
 *
 * @text This example implements a minimal HID-over-GATT Host. It scans for LE HID devices, connects to it,
 * discovers the Characteristics relevant for the HID Service and enables Notifications on them.
 * It then dumps all Boot Keyboard and Mouse Input Reports
 */

#include <inttypes.h>
#include <stdio.h>
#include <btstack_tlv.h>

#include "btstack_config.h"
#include "btstack.h"

// hog_host_demo.gatt contains the declaration of the provided GATT Services + Characteristics
// hog_host_demo.h    contains the binary representation of gatt_browser.gatt
// it is generated by the build system by calling: $BTSTACK_ROOT/tool/compile_gatt.py hog_host_demo.gatt hog_host_demo.h
// it needs to be regenerated when the GATT Database declared in gatt_browser.gatt file is modified
#include "hog_host_demo.h"
#include "bt_example_common.h"
#include "pico/cyw43_arch.h"
#include "Common.h"
#include "bridge_control.h"

//--------------------------------------------------------------------+
// CONSTANTS & TYPES
//--------------------------------------------------------------------+
// Timeout constants
#define CONNECTION_TIMEOUT_MS 3000  // 3 seconds for connection attempt
#define SCAN_TIMEOUT_MS       5000  // 5 seconds for scanning
#define CONTROL_POLL_MS       50

// Connection parameters requested once the link is encrypted. Peripherals are
// free to advertise a slow, power-saving interval; for an input device the
// round trip is what the user feels, so ask for the shortest interval the LE
// spec allows a peripheral to be required to honour.
#define CONN_INTERVAL_MIN_UNITS 10  // x 1.25 ms = 12.5 ms
#define CONN_INTERVAL_MAX_UNITS 12  // x 1.25 ms = 15 ms
#define CONN_LATENCY_EVENTS     0   // no skipped connection events
#define CONN_TIMEOUT_UNITS      300 // x 10 ms = 3 s supervision timeout

// TAG to store remote device address and type in TLV
#define TLV_TAG_HOGD ((((uint32_t) 'H') << 24 ) | (((uint32_t) 'O') << 16) | (((uint32_t) 'G') << 8) | 'D')

typedef struct {
    bd_addr_t addr;
    bd_addr_type_t addr_type;
} le_device_addr_t;

static enum {
    W4_WORKING,
    W4_HID_DEVICE_FOUND,
    W4_CONNECTED,
    W4_ENCRYPTED,
    W4_HID_CLIENT_CONNECTED,
    READY,
    W4_FORGETTING,
    W4_TIMEOUT_THEN_SCAN,
    W4_TIMEOUT_THEN_RECONNECT,
} app_state;

//--------------------------------------------------------------------+
// GLOBAL & STATIC VARIABLES
//--------------------------------------------------------------------+
static le_device_addr_t remote_device;
static hci_con_handle_t connection_handle = HCI_CON_HANDLE_INVALID;
static uint16_t hids_cid;
static hid_protocol_mode_t protocol_mode = HID_PROTOCOL_MODE_REPORT;

// SDP: The whole HID report descriptor of the remote device is cached here and later
// handed to the USB host verbatim. Keyboards with media keys, multi-device
// switching or vendor collections run well past the 500 bytes the BTstack
// example assumes, and the surplus is silently dropped, so give it 2 KB.
static uint8_t hid_descriptor_storage[2048];
// BTstack releases its descriptor on disconnect. USB keeps the first descriptor
// acquired after boot so BLE reconnects do not change the enumerated device.
static uint8_t usb_hid_report_descriptor[sizeof(hid_descriptor_storage)];
static volatile uint16_t usb_hid_report_descriptor_len;

// Used to implement connection timeout and reconnect timer
static btstack_timer_source_t connection_timer;
static btstack_timer_source_t control_timer;
static bool replacing_keyboard;

// Register for events from HCI/GAP and SM
static btstack_packet_callback_registration_t hci_event_callback_registration;
static btstack_packet_callback_registration_t sm_event_callback_registration;

// Used to store remote device in TLV
static const btstack_tlv_t * btstack_tlv_singleton_impl;
static void * btstack_tlv_singleton_context;

extern volatile bool g_usb_reinit_request;

//--------------------------------------------------------------------+
// FUNCTION PROTOTYPES
//--------------------------------------------------------------------+
void ble_host_main(void);
bool is_ble_app_state_ready(void);
const uint8_t* get_ble_hid_report_descriptor_data(void);
uint16_t get_ble_hid_report_descriptor_len(void);
int btstack_main(int argc, const char * argv[]);

static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);

static void hog_start_connect(void);
static void hog_connect(void);
static void hog_start_scan(void);
static void hog_scan_timeout(btstack_timer_source_t * ts);
static void hog_connection_timeout(btstack_timer_source_t * ts);
static void handle_outgoing_connection_error(void);
static void request_hid_connection_parameters(void);
static void activate_usb_hid_descriptor(void);
static void control_timer_handler(btstack_timer_source_t *ts);
static void start_keyboard_replacement(void);
static void finish_keyboard_replacement(void);
static bool adv_event_contains_hid_service(const uint8_t * packet);

static void hid_handle_input_report(uint8_t service_index, uint8_t report_id, const uint8_t * report, uint16_t report_len);

//--------------------------------------------------------------------+
// PUBLIC APIs & ENTRY POINTS
//--------------------------------------------------------------------+

/**
 * @brief Main function for the BLE host task (runs on Core1).
 * @note This function initializes and runs the BTstack event loop.
 */
void ble_host_main(void)
{
    // Initialize BTstack for the current board
    (void)ble_bridge_bt_example_init();
    // Set up and start the main BTstack task
    ble_bridge_bt_example_main();
    // Enter the BTstack run loop
    btstack_run_loop_execute();
}

/**
 * @brief Check if the BLE application state is READY.
 * @return true if the application state is READY, false otherwise.
 */
bool is_ble_app_state_ready(void)
{
    return (READY == app_state) ? true : false;
}

/**
 * @brief Get the pointer to the HID Report Descriptor received via BLE.
 * @return Pointer to the HID Report Descriptor data.
 */
const uint8_t* get_ble_hid_report_descriptor_data(void)
{
    if (usb_hid_report_descriptor_len == 0) {
        return NULL;
    }

    return usb_hid_report_descriptor;
}

/**
 * @brief Get the length of the HID Report Descriptor received via BLE.
 * @return Length of the HID Report Descriptor.
 */
uint16_t get_ble_hid_report_descriptor_len(void)
{
    return usb_hid_report_descriptor_len;
}

//--------------------------------------------------------------------+
// INITIALIZATION
//--------------------------------------------------------------------+

/**
 * @brief Initialize and start the BTstack setup for HID host.
 * @param argc Argument count.
 * @param argv Argument vector.
 * @return Status code (0 on success).
 */
int btstack_main(int argc, const char * argv[])
{
    (void)argc;
    (void)argv;

    l2cap_init();

    // setup SM: Display only
    sm_init();
    sm_set_io_capabilities(IO_CAPABILITY_DISPLAY_ONLY);
    sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);

    gatt_client_init();

    // setup ATT server - only needed if LE Peripheral does ATT queries on its own, e.g. Android and iOS
    att_server_init(profile_data, NULL, NULL);

    hids_client_init(hid_descriptor_storage, sizeof(hid_descriptor_storage));

    // register for events from HCI
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    // register for events from Security Manager
    sm_event_callback_registration.callback = &sm_packet_handler;
    sm_add_event_handler(&sm_event_callback_registration);

    // Disable stdout buffering
    setvbuf(stdin, NULL, _IONBF, 0);

    app_state = W4_WORKING;
    bridge_control_publish_state(BRIDGE_STATE_STARTING);

    // Turn on the device
    hci_power_control(HCI_POWER_ON);

    btstack_run_loop_set_timer_handler(&control_timer, control_timer_handler);
    btstack_run_loop_set_timer(&control_timer, CONTROL_POLL_MS);
    btstack_run_loop_add_timer(&control_timer);
    return 0;
}

//--------------------------------------------------------------------+
// EVENT HANDLERS
//--------------------------------------------------------------------+

/**
 * @brief HCI and GAP event packet handler.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(channel);
    UNUSED(size);
    uint8_t event;

    switch (packet_type) {
        case HCI_EVENT_PACKET:
            event = hci_event_packet_get_type(packet);
            switch (event) {
                case BTSTACK_EVENT_STATE:
                    if (btstack_event_state_get_state(packet) != HCI_STATE_WORKING) break;
                    btstack_assert(app_state == W4_WORKING);
                    
                    hog_start_connect();
                    break;
                case GAP_EVENT_ADVERTISING_REPORT:
                    if (app_state != W4_HID_DEVICE_FOUND) break;
                    if (adv_event_contains_hid_service(packet) == false) break;
                    
                    // Stop scan timeout timer and stop scan
                    btstack_run_loop_remove_timer(&connection_timer);
                    gap_stop_scan();

                    // store remote device address and type
                    gap_event_advertising_report_get_address(packet, remote_device.addr);
                    remote_device.addr_type = gap_event_advertising_report_get_address_type(packet);
                    
                    BLE_LOG("Found HID device %s, connecting...\n", bd_addr_to_str(remote_device.addr));
                    hog_connect();
                    break;
                case HCI_EVENT_DISCONNECTION_COMPLETE:
                    connection_handle = HCI_CON_HANDLE_INVALID;
                    BLE_LOG("Disconnected, starting over...\n");
                    bridge_control_clear_passkey();
                    
                    // Fix: Ensure timer is cleared upon disconnection before starting over
                    btstack_run_loop_remove_timer(&connection_timer);

                    if (replacing_keyboard) {
                        finish_keyboard_replacement();
                        break;
                    }

                    bridge_control_publish_state(BRIDGE_STATE_DISCONNECTED);
                    app_state = W4_WORKING;
                    hog_start_connect();
                    break;
                case HCI_EVENT_META_GAP:
                    // wait for connection complete
                    if (hci_event_gap_meta_get_subevent_code(packet) != GAP_SUBEVENT_LE_CONNECTION_COMPLETE) break;
                    if (app_state != W4_CONNECTED) return;
                    btstack_run_loop_remove_timer(&connection_timer);
                    connection_handle = gap_subevent_le_connection_complete_get_connection_handle(packet);
                    // request security
                    app_state = W4_ENCRYPTED;
                    bridge_control_publish_state(BRIDGE_STATE_PAIRING);
                    sm_request_pairing(connection_handle);
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}

/**
 * @brief Security Manager (SM) packet handler for pairing and re-encryption events.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void sm_packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(channel);
    UNUSED(size);

    if (packet_type != HCI_EVENT_PACKET) return;

    bool connect_to_service = false;

    switch (hci_event_packet_get_type(packet)) {
        case SM_EVENT_JUST_WORKS_REQUEST:
            BLE_LOG("Just works requested\n");
            sm_just_works_confirm(sm_event_just_works_request_get_handle(packet));
            break;
        case SM_EVENT_NUMERIC_COMPARISON_REQUEST:
            BLE_LOG("Confirming numeric comparison: %"PRIu32"\n", sm_event_numeric_comparison_request_get_passkey(packet));
            sm_numeric_comparison_confirm(sm_event_passkey_display_number_get_handle(packet));
            break;
        case SM_EVENT_PASSKEY_DISPLAY_NUMBER: {
            uint32_t passkey = sm_event_passkey_display_number_get_passkey(packet);
            bridge_control_publish_passkey(passkey);
            BLE_LOG("Display Passkey: %"PRIu32"\n", passkey);
            break;
        }
        case SM_EVENT_PAIRING_COMPLETE:
            switch (sm_event_pairing_complete_get_status(packet)){
                case ERROR_CODE_SUCCESS:
                    BLE_LOG("Pairing complete, success\n");
                    request_hid_connection_parameters();
                    connect_to_service = true;
                    break;
                case ERROR_CODE_CONNECTION_TIMEOUT:
                    BLE_LOG("Pairing failed, timeout\n");
                    handle_outgoing_connection_error();
                    break;
                default:
                    BLE_LOG("Pairing failed, status 0x%02x\n", sm_event_pairing_complete_get_status(packet));
                    handle_outgoing_connection_error();
                    break;
            }
            break;
        case SM_EVENT_REENCRYPTION_COMPLETE:
            BLE_LOG("Re-encryption complete, success\n");
            request_hid_connection_parameters();
            connect_to_service = true;
            break;
        default:
            break;
    }

    if (connect_to_service){
        // continue - query primary services
        BLE_LOG("Search for HID service.\n");
        app_state = W4_HID_CLIENT_CONNECTED;
        bridge_control_publish_state(BRIDGE_STATE_DISCOVERING);
        hids_client_connect(connection_handle, handle_gatt_client_event, protocol_mode, &hids_cid);
    }
}

/**
 * @brief Handle GATT Client events dependent on current application state.
 * @param packet_type Type of incoming packet.
 * @param channel Channel ID.
 * @param packet Pointer to packet payload.
 * @param size Size of packet.
 */
static void handle_gatt_client_event(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(packet_type);
    UNUSED(channel);
    UNUSED(size);

    uint8_t status;

    if (hci_event_packet_get_type(packet) != HCI_EVENT_GATTSERVICE_META){
        return;
    }
    
    switch (hci_event_gattservice_meta_get_subevent_code(packet)){
        case GATTSERVICE_SUBEVENT_HID_SERVICE_CONNECTED:
            status = gattservice_subevent_hid_service_connected_get_status(packet);
            switch (status){
                case ERROR_CODE_SUCCESS:
                    BLE_LOG("HID service client connected, found %d services\n", 
                        gattservice_subevent_hid_service_connected_get_num_instances(packet));
        
                    // store device as bonded
                    if (btstack_tlv_singleton_impl){
                        btstack_tlv_singleton_impl->store_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (const uint8_t *) &remote_device, sizeof(remote_device));
                    }
                    // done
                    BLE_LOG("Ready - please start typing or mousing..\n");
                    app_state = READY;
                    bridge_control_clear_passkey();
                    bridge_control_publish_state(BRIDGE_STATE_READY);
                    activate_usb_hid_descriptor();
                    break;
                default:
                    BLE_LOG("HID service client connection failed, status 0x%02x.\n", status);
                    handle_outgoing_connection_error();
                    break;
            }
            break;

        case GATTSERVICE_SUBEVENT_HID_SERVICE_DISCONNECTED:
            BLE_LOG("HID service client disconnected\n");
            break;

        case GATTSERVICE_SUBEVENT_HID_REPORT:
            hid_handle_input_report(
                gattservice_subevent_hid_report_get_service_index(packet),
                gattservice_subevent_hid_report_get_report_id(packet), 
                gattservice_subevent_hid_report_get_report(packet), 
                gattservice_subevent_hid_report_get_report_len(packet));
            break;

        default:
            break;
    }
}

//--------------------------------------------------------------------+
// CONNECTION & SCANNING CONTROL
//--------------------------------------------------------------------+

/**
 * @brief Start connecting after boot up: connect to last used device if possible, start scan otherwise.
 */
static void hog_start_connect(void)
{
    // check if we have a bonded device
    btstack_tlv_get_instance(&btstack_tlv_singleton_impl, &btstack_tlv_singleton_context);
    if (btstack_tlv_singleton_impl){
        int len = btstack_tlv_singleton_impl->get_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD, (uint8_t *) &remote_device, sizeof(remote_device));
        if (len == sizeof(remote_device)){
            BLE_LOG("Bonded device found, trying to connect...\n");
            hog_connect();
            return;
        }
    }
    // otherwise, scan for HID devices
    hog_start_scan();
}

/**
 * @brief Connect to remote device with a connection timeout timer.
 */
static void hog_connect(void)
{
    BLE_LOG("Connecting to device %s (Timeout %dms)...\n", bd_addr_to_str(remote_device.addr), CONNECTION_TIMEOUT_MS);
    bridge_control_clear_passkey();
    bridge_control_publish_state(BRIDGE_STATE_CONNECTING);
    
    // Fix: Remove timer before adding. If a previous timer (like scan timeout) is still active, 
    // btstack_run_loop_add_timer would trigger an assertion failure.
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer for connection attempt
    btstack_run_loop_set_timer(&connection_timer, CONNECTION_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_connection_timeout);
    btstack_run_loop_add_timer(&connection_timer);
    
    app_state = W4_CONNECTED;
    gap_connect(remote_device.addr, remote_device.addr_type);
}

/**
 * @brief Start scanning for LE HID devices.
 */
static void hog_start_scan(void)
{
    BLE_LOG("Scanning for LE HID devices (Timeout %dms)...\n", SCAN_TIMEOUT_MS);
    app_state = W4_HID_DEVICE_FOUND;
    bridge_control_clear_passkey();
    bridge_control_publish_state(BRIDGE_STATE_SCANNING);

    // Fix: Remove timer before adding to prevent assertion if scan is restarted during reconnection
    btstack_run_loop_remove_timer(&connection_timer);

    // Set timer to stop scanning and try connecting to bonded device
    btstack_run_loop_set_timer(&connection_timer, SCAN_TIMEOUT_MS);
    btstack_run_loop_set_timer_handler(&connection_timer, &hog_scan_timeout);
    btstack_run_loop_add_timer(&connection_timer);

    // Passive scanning, 100% (scan interval = scan window)
    gap_set_scan_parameters(0,48,48);
    gap_start_scan();
}

/**
 * @brief Handle scan timeout by stopping scan and attempting connection to bonded device.
 * @param ts Pointer to timer source structure.
 */
static void hog_scan_timeout(btstack_timer_source_t * ts)
{
    UNUSED(ts);
    if (app_state != W4_HID_DEVICE_FOUND) return;
    BLE_LOG("Scan timeout. Switching to bonded connection attempt...\n");
    gap_stop_scan();
    hog_start_connect();
}

/**
 * @brief Handle connection timeout by cancelling connection attempt and restarting scan.
 * @param ts Pointer to timer source structure.
 */
static void hog_connection_timeout(btstack_timer_source_t * ts)
{
    UNUSED(ts);
    BLE_LOG("Connection timeout. Switching to scan...\n");
    gap_connect_cancel();
    hog_start_scan();
}

/**
 * @brief Handle connection error by disconnecting and restarting scan.
 */
static void handle_outgoing_connection_error(void)
{
    BLE_LOG("Error occurred, disconnect and start over\n");
    gap_disconnect(connection_handle);
    hog_start_scan();
}

/**
 * @brief Request optimized connection parameters for HID device.
 */
static void request_hid_connection_parameters(void)
{
    if (connection_handle == HCI_CON_HANDLE_INVALID) return;
    gap_request_connection_parameter_update(connection_handle,
                                            CONN_INTERVAL_MIN_UNITS,
                                            CONN_INTERVAL_MAX_UNITS,
                                            CONN_LATENCY_EVENTS,
                                            CONN_TIMEOUT_UNITS);
}

/**
 * @brief Copy the connected BLE HID device's report descriptor into the USB-facing
 *        buffer and request USB re-enumeration if it differs from the active one.
 */
static void activate_usb_hid_descriptor(void)
{
    const uint8_t * descriptor = hids_client_descriptor_storage_get_descriptor_data(hids_cid, 0);
    uint16_t descriptor_len = hids_client_descriptor_storage_get_descriptor_len(hids_cid, 0);
    if (descriptor == NULL || descriptor_len == 0 ||
        descriptor_len > sizeof(usb_hid_report_descriptor)) {
        return;
    }

    if (usb_hid_report_descriptor_len == descriptor_len &&
        memcmp(usb_hid_report_descriptor, descriptor, descriptor_len) == 0) {
        return;
    }

    memcpy(usb_hid_report_descriptor, descriptor, descriptor_len);
    usb_hid_report_descriptor_len = descriptor_len;
    g_usb_reinit_request = true;
}

/**
 * @brief Periodic timer callback that polls for a pending "pair new keyboard"
 *        request from the Web Serial control UI and reschedules itself.
 */
static void control_timer_handler(btstack_timer_source_t *ts)
{
    UNUSED(ts);
    if (app_state != W4_WORKING && bridge_control_take_pair_new_request()) {
        start_keyboard_replacement();
    }

    btstack_run_loop_set_timer(&control_timer, CONTROL_POLL_MS);
    btstack_run_loop_add_timer(&control_timer);
}

/**
 * @brief Begin forgetting the currently paired keyboard so a new one can be
 *        scanned for and paired. Disconnects first if a link is active;
 *        otherwise finishes the replacement immediately.
 */
static void start_keyboard_replacement(void)
{
    if (replacing_keyboard) {
        return;
    }

    replacing_keyboard = true;
    app_state = W4_FORGETTING;
    bridge_control_clear_passkey();
    bridge_control_publish_state(BRIDGE_STATE_FORGETTING);
    btstack_run_loop_remove_timer(&connection_timer);
    gap_stop_scan();

    if (connection_handle != HCI_CON_HANDLE_INVALID) {
        gap_disconnect(connection_handle);
        return;
    }

    gap_connect_cancel();
    finish_keyboard_replacement();
}

/**
 * @brief Erase the stored HOGD bonding data and remembered device address,
 *        then restart scanning for a new BLE HID keyboard to pair with.
 */
static void finish_keyboard_replacement(void)
{
    if (btstack_tlv_singleton_impl != NULL) {
        btstack_tlv_singleton_impl->delete_tag(btstack_tlv_singleton_context, TLV_TAG_HOGD);
    }

    gap_delete_bonding(remote_device.addr_type, remote_device.addr);

    memset(&remote_device, 0, sizeof(remote_device));
    connection_handle = HCI_CON_HANDLE_INVALID;
    replacing_keyboard = false;
    CMN_ClearQueue(CMN_QUE_KIND_HID_RPT);
    hog_start_scan();
}

/**
 * @brief Check if advertising event packet contains HID service UUID.
 * @param packet Pointer to advertising report packet.
 * @return true if HID service UUID is found, false otherwise.
 */
static bool adv_event_contains_hid_service(const uint8_t * packet)
{
    const uint8_t * ad_data = gap_event_advertising_report_get_data(packet);
    uint8_t ad_len = gap_event_advertising_report_get_data_length(packet);
    return ad_data_contains_uuid16(ad_len, ad_data, ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE);
}

//--------------------------------------------------------------------+
// HID REPORT HANDLING
//--------------------------------------------------------------------+

/**
 * @brief Process and enqueue received BLE HID input report.
 * @param service_index Index of the HID service.
 * @param report_id Report ID of the input report.
 * @param report Pointer to report data.
 * @param report_len Length of report data.
 */
static void hid_handle_input_report(uint8_t service_index, uint8_t report_id, const uint8_t * report, uint16_t report_len)
{
    // A report can arrive before the connection event during a fast reconnect.
    // Keep report handling live without re-enumerating an already active USB device.
    if (app_state != READY) {
        BLE_LOG("HID report received in state %d. Forcing app_state to READY.\n", app_state);
        app_state = READY;
        bridge_control_clear_passkey();
        bridge_control_publish_state(BRIDGE_STATE_READY);
        activate_usb_hid_descriptor();
    }
    
    // Enqueue the raw report for the USB task.
    // The USB HID task manages transmission to the host.
    static ST_HID_RPT stHidRpt; // Change local variable to static to use static memory (data area) instead of stack, preventing stack overflow.

    stHidRpt.report_id  = report_id;
    stHidRpt.report_len = report_len;  
    // Prevent buffer overflow if the report is larger than the buffer
    if (stHidRpt.report_len > CMN_HID_RPT_DATA_SIZE) {
        stHidRpt.report_len = CMN_HID_RPT_DATA_SIZE;
    }
    memcpy(stHidRpt.report, report, stHidRpt.report_len);
    if (!CMN_Enqueue(CMN_QUE_KIND_HID_RPT, &stHidRpt)) {
        // Queue is full
    }
    return;
}

/* EXAMPLE_END */
